name = "gestor-deudas"
compatibility_date = "2025-01-01"

# Requerido para que Pages lea este archivo como config vÃ¡lida.
pages_build_output_dir = "public"

# Cloudflare Pages: assets en /public y Functions en /functions

[[d1_databases]]
binding = "DB"
database_name = "gestor_deudas_db"
database_id = "c478684a-6c0f-41b0-bd30-cd128b1cbb00"
